language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-fullmvc' ]; then cd .. && eval "mv $currentfolder generator-fullmvc" && cd generator-fullmvc; fi

